name: example
description: Example using bottom sheet.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bottom_sheet:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  surf_lint_rules: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
